
version: 2

models:
  - name: new_folder_demo
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
  - name: orders
    description: "customer orders "
    columns:
      - name: order_id
        description: "Primary key for the orders table"
        tests:
          - unique
          - not_null

  